---
name: release
on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-22.04
    steps:
      - uses: google-github-actions/release-please-action@vdb8f2c60ee802b3748b512940dde88eabd7b7e01 # v3.7.13
        with:
          release-type: go
          package-name: go-ethtool-metrics
