---
name: tests
on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: tests
  cancel-in-progress: true

env:
  COVERAGE_THRESHOLD: 96.7

jobs:
  test_go:
    name: Go tests
    runs-on: ubuntu-24.04
    container:
      image: quay.io/prometheus/golang-builder:1.23-base
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Run tests
        run: go test ./... -coverpkg=github.com/newrushbolt/go-ethtool-metrics/... -coverprofile coverage.out

      - name: Get coverage filtering package
        run: go install github.com/quantumcycle/go-ignore-cov@v0.6.1
      - name: Filter coverage
        run: go-ignore-cov -v --file coverage.out

      - name: Show coverage report per-function
        run: go tool cover -func coverage.out
      - name: Check total coverage threshold
        run: |
              echo "Coverage threshold: $COVERAGE_THRESHOLD %"
              totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
              echo "Current test coverage: $totalCoverage %"
              if awk "BEGIN {exit !($totalCoverage >= $COVERAGE_THRESHOLD)}"; then
                  echo "OK"
              else
                  echo "Current test coverage is below threshold"
                  exit 1
              fi
