---
name: tests
on:
  pull_request:
  push:

jobs:
  test_go:
    name: Go tests
    runs-on: ubuntu-24.04
    container:
      image: quay.io/prometheus/golang-builder:1.23-base
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - run: go test -v
