---
name: tests
on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: tests
  cancel-in-progress: true

jobs:
  test_go:
    name: Go tests
    runs-on: ubuntu-24.04
    container:
      image: quay.io/prometheus/golang-builder:1.23-base
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - run: >-
          go test ./...
          -coverpkg=github.com/newrushbolt/go-ethtool-metrics/...
          -coverprofile coverage.out
          -covermode count
      - run: go tool cover -func coverage.out
      # TODO: set coverage threshold, eg https://github.com/lluuiissoo/go-testcoverage/blob/main/.github/workflows/ci.yml
